@OrdersApi_HostAddress = http://localhost:5121

### Create an order
POST {{OrdersApi_HostAddress}}/orders
Content-Type: application/json

{
  "type": "Standard",
  "originalValue": 10.0,
  "debitedValue": 8.50,
  "products": ["c100f88f-aedb-428a-a9ee-f8cf3b10af66"],
  "user": "jean@itau.com",
  "trackingURL": "https://www.guidgenerator.com"
}

###

### Get an order by ID
GET {{OrdersApi_HostAddress}}/orders/385141a7-42ca-495c-8f7c-09d33e6c6e73
Accept: application/json

###

### Add item to an order
PUT {{OrdersApi_HostAddress}}/orders/385141a7-42ca-495c-8f7c-09d33e6c6e73/items/9f5b8f41-79a6-4bed-b8ff-a7ec686fc6ab
Accept: application/json

###

### Remove item from an order
DELETE {{OrdersApi_HostAddress}}/orders/385141a7-42ca-495c-8f7c-09d33e6c6e73/items/9f5b8f41-79a6-4bed-b8ff-a7ec686fc6ab
Accept: application/json

###

### Create a product
POST {{OrdersApi_HostAddress}}/products
Content-Type: application/json

{
  "imageURL": "https://www.guidgenerator.com",
  "description": "Bola de futebol",
  "price": 20.0
}

###

### Get a product by ID
GET {{OrdersApi_HostAddress}}/products/c100f88f-aedb-428a-a9ee-f8cf3b10af66
Accept: application/json

###
